# Generated by Django 4.2.7 on 2024-01-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('SF', 'サイエンスフィクション'), ('Action', 'アクション'), ('Horror', 'ホラー'), ('Documentary', 'ドキュメンタリー'), ('animation', 'アニメーション'), ('thriller', 'スリラー'), ('Drama', 'ドラマ'), ('Comedy', 'コメディ'), ('Adventure', 'アドベンチャー'), ('other', 'その他')], max_length=100)),
            ],
        ),
    ]
