# Generated by Django 4.2.7 on 2024-01-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category2',
            field=models.CharField(choices=[('邦画', 'japan'), ('洋画', 'world'), ('アニメ', 'anime')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('サイエンスフィクション', 'SF'), ('アクション', 'Action'), ('ホラー', 'Horror'), ('ドキュメンタリー', 'Documentary'), ('スリラー', 'thriller'), ('ドラマ', 'Drama'), ('コメディ', 'Comedy'), ('アドベンチャー', 'Adventure'), ('その他', 'other')], max_length=100),
        ),
    ]
