# Generated by Django 4.2.7 on 2024-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
