# Generated by Django 4.2.7 on 2024-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category2',
            field=models.CharField(choices=[('邦画', '1'), ('洋画', '2'), ('アニメ', '3')], max_length=100),
        ),
    ]
