# Generated by Django 4.2.7 on 2024-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category2',
            field=models.CharField(choices=[('邦画', 'japan'), ('洋画', 'world'), ('アニメ', 'anime')], max_length=100),
        ),
    ]
